=== markharrison/azure1/az1schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",
  "type": "object",
  "required": [ "name", "version" ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "product": {
      "type": "object",
      "required": [ "name", "categories" ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [ "name", "icon", "services" ],
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string"
              },
              "icon": {
                "type": "string"
              },
              "services": {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": [ "name", "icon" ],
                  "additionalProperties": false,
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "icon": {
                      "type": "string"
                    },
                    "service": {
                      "type": "string",
                      "optional": true
                    },
                    "feature": {
                      "type": "string",
                      "optional": true
                    },
                    "pricing": {
                      "type": "string",
                      "optional": true
                    },
                    "docs": {
                      "type": "string",
                      "optional": true
                    },
                    "text": {
                      "type": "string",
                      "optional": true
                    },
                    "content": {
                      "type": "array",
                      "optional": true,
                      "items": {
                        "type": "object",
                        "required": [ "item" ],
                        "properties": {
                          "item": {
                            "type": "string",
                            "oneOf": [
                              {
                                "type": "string",
                                "enum": [ "link", "space", "ppt", "pdf", "YTvideo", "C9video","slide" ]
                              }
                            ]
                          },
                          "text": {
                            "type": "string",
                            "optional": true
                          },
                          "url": {
                            "type": "string",
                            "optional": true
                          }
                        }
                      }

                    },
                    "related": {
                      "type": "array",
                      "optional": true,
                      "items": {
                        "type": "object",
                        "required": [ "name" ],
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "icon": {
                            "type": "string",
                            "optional": true
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== markharrison/azure1/az1data.json
{
  "author": "Mark Harrison",
  "name": "azure1.dev",
  "version": "2022.12.23",
  "product": {
    "name": "Azure",
    "categories": [
      {
        "name": "Trustworthiness",
        "icon": "trustworthiness",
        "services": [
          {
            "name": "Hyper-Scale",
            "icon": "reliability",
            "content": [
              {
                "item": "link",
                "text": "Azure Regions",
                "url": "*ams*/global-infrastructure/geographies/"
              },
              {
                "item": "link",
                "text": "Azure Infrastructure Map",
                "url": "https://infrastructuremap.microsoft.com/"
              },
              {
                "item": "link",
                "url": "*ams*/roadmap/",
                "text": "Azure roadmap"
              },
              {
                "item": "YTvideo",
                "text": "Microsoft Global Datacenters and Network Infrastructure",
                "url": "koSKZRfxkIA"
              },
              {
                "item": "YTvideo",
                "text": "Inside Azure datacenter architecture",
                "url": "69PrhWQorEM"
              }

            ]
          },
          {
            "name": "Leadership",
            "icon": "vision",
            "content": [
              {
                "item": "link",
                "url": "www.microsoft.com/en-us/legal/compliance/sbc/default.aspx",
                "text": "Standards of Business Conduct"
              },
              {
                "item": "link",
                "url": "www.microsoft.com/en-us/AI/our-approach-to-ai",
                "text": "Microsoft AI principles"
              },
              {
                "item": "space"

              },
              {
                "item": "link",
                "text": "Azure IP Advantage - Protecting Innovation",
                "url": "*ams*/overview/azure-ip-advantage/"
              },
              {
                "item": "YTvideo",
                "text": "IP Advantage",
                "url": "qRQqYn1mmG8"
              }
            ]
          },
          {
            "name": "Security",
            "icon": "security",
            "content": [
              {
                "item": "link",
                "url": "www.microsoft.com/trustcenter",
                "text": "Overview - Security"
              },
              {
                "item": "link",
                "text": "Documentation - Azure Security",
                "url": "*docs*/security/azure-security-getting-started"
              },
              {
                "item": "link",
                "url": "*ams*/en-gb/marketplace/?term=security",
                "text": "Marketplace - Security"
              },
              {
                "item": "YTvideo",
                "text": "Next Generation Windows Security Vision",
                "url": "IvZySDNfNpo"
              },
              {
                "item": "link",
                "text": "Cybersecurity Resources @MarkSimos",
                "url": "aka.ms/markslist"
              }
            ],
            "related": [
              {
                "name": "Sentinel"
              },
              {
                "name": "Security Center"
              },
              {
                "name": "Enterprise Mobility and Security Suite"
              },
              {
                "name": "Dedicated HSM"
              },
              {
                "name": "Azure Key Vault"
              }
            ]
          },
          {
            "name": "Transparency",
            "icon": "transparency",
            "content": [
              {
                "item": "link",
                "url": "www.microsoft.com/en-us/trustcenter/about/transparency",
                "text": "Overview - Transparency"
              }
            ]
          },
          {
            "name": "Regulatory Compliance",
            "icon": "regulatory",
            "content": [
              {
                "item": "link",
                "url": "www.microsoft.com/en-us/trustcenter/compliance",
                "text": "Overview - Compliance"
              },
              {
                "item": "link",
                "url": "servicetrust.microsoft.com",
                "text": "Compliance Reports - Service Trust Portal"
              }

            ]
          },
          {
            "name": "Privacy",
            "icon": "privacy",
            "content": [
              {
                "item": "link",
                "url": "www.microsoft.com/en-us/TrustCenter/Privacy",
                "text": "Overview - Privacy"
              },
              {
                "item": "link",
                "url": "www.microsoft.com/gdpr",
                "text": "General Data Protection Regulation (GDPR)"
              }
            ]
          },

          {
            "name": "Environmental Sustainability",
            "icon": "environment",
            "content": [
              {
                "item": "link",
                "url": "*ams*/global-infrastructure/sustainability/",
                "text": "Azure sustainability"
              },
              {
                "item": "link",
                "url": "*ms*/en-us/corporate-responsibility/sustainability",
                "text": "Microsoft Corporate Responsibility"
              },
              {
                "item": "link",
                "url": "*ms*/aiforearth",
                "text": "AI for Earth"
              },
              {
                "item": "link",
                "url": "https://devblogs.microsoft.com/sustainable-software/",
                "text": "Sustainable Software blog"
              },
              {
                "item": "link",
                "url": "https://cloudblogs.microsoft.com/industry-blog/en-gb/technetuk/2021/08/19/sustainability-and-green-software-engineering/",
                "text": "Sustainability and Green Software Engineering"
              },
              {
                "item": "YTvideo",
                "url": "Tcvr30NRWmA",
                "text": "Green Software Engineering"
              }
            ]
          },
          {
            "name": "Support",
            "icon": "support",
            "content": [
              {
                "item": "link",
                "url": "*ams*/support/plans/",
                "text": "Support plans"
              },
              {
                "item": "link",
                "url": "*ams*/offers/enterprise-agreement-support-upgrade",
                "text": "EA Support free upgrade"
              }
            ]
          },
          {
            "name": "Partner Ecosystem",
            "icon": "partnership",
            "content": [
              {
                "item": "link",
                "url": "*ams*/partners/directory/",
                "text": "Technology and service partners"
              },
              {
                "item": "link",
                "url": "https://azuremarketplace.microsoft.com/marketplace/apps",
                "text": "Azure Marketplace"
              },
              {
                "item": "link",
                "url": "partner.microsoft.com",
                "text": "Partner Network"
              },
              {
                "item": "link",
                "url": "partner.microsoft.com/cloud-solution-provider/",
                "text": "Cloud Solution Provider program"
              }
            ]
          },
          {
            "name": "Research",
            "icon": "research",
            "content": [
              {
                "item": "link",
                "url": "microsoft.com/research",
                "text": "Microsoft Research"
              }
            ]
          }
        ]
      },
      {
        "name": "Compute",
        "icon": "compute",
        "services": [
          {
            "name": "Virtual Machines",
            "icon": "virtualmachine",
            "text": "Windows Server and Linux virtual machines",
            "content": [
              {
                "item": "link",
                "url": "*service*/virtual-machines/"
              },
              {
                "item": "link",
                "url": "*ams*/pricing/hybrid-benefit/",
                "text": "Azure Hybrid Benefit"
              },
              {
                "item": "link",
                "url": "*pricing*/virtual-machines/windows",
                "text": "Windows VMs Pricing"
              },
              {
                "item": "link",
                "url": "*docs*/virtual-machines/windows",
                "text": "Windows VMs Documentation"
              },
              {
                "item": "link",
                "url": "*pricing*/virtual-machines/linux",
                "text": "Linux VMsPricing"
              },
              {
                "item": "link",
                "url": "*docs*/virtual-machines/linux",
                "text": "Linux VMs Documentation"
              },
              {
                "item": "space"
              },
              {
                "item": "link",
                "url": "www.azureprice.net",
                "text": "Azure VM Comparison / Pricer"
              }
            ],

            "related": [
              {
                "name": "VM Scale Sets"
              },
              {
                "name": "VM Image Builder"
              },
              {
                "name": "Windows VMs",
                "icon": "vmwindows"
              },
              {
                "name": "LINUX VMs",
                "icon": "vmlinux"
              },
              {

                "name": "Azure Dedicated Host"
              }
            ]
          },
          {
            "name": "Azure Dedicated Host",
            "icon": "dedicatedhost",
